// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhncqxS-Wvjl3QcTbBsDaoYgv7O_FsXPo',
    appId: '1:290504350182:web:054c25292bb60d31b89e27',
    messagingSenderId: '290504350182',
    projectId: 'biblio-mobile-app',
    authDomain: 'biblio-mobile-app.firebaseapp.com',
    storageBucket: 'biblio-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhjWsMMuHKjGJXshZoZ2FG9hCzfzP55cY',
    appId: '1:290504350182:android:fad5ec71fc306190b89e27',
    messagingSenderId: '290504350182',
    projectId: 'biblio-mobile-app',
    storageBucket: 'biblio-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-7rfSkALGlbQCZJW9lHNthF4-UoboZ_M',
    appId: '1:290504350182:ios:d972453e1268f912b89e27',
    messagingSenderId: '290504350182',
    projectId: 'biblio-mobile-app',
    storageBucket: 'biblio-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.biblio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-7rfSkALGlbQCZJW9lHNthF4-UoboZ_M',
    appId: '1:290504350182:ios:d972453e1268f912b89e27',
    messagingSenderId: '290504350182',
    projectId: 'biblio-mobile-app',
    storageBucket: 'biblio-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.biblio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhncqxS-Wvjl3QcTbBsDaoYgv7O_FsXPo',
    appId: '1:290504350182:web:f78da7fb3149dd8cb89e27',
    messagingSenderId: '290504350182',
    projectId: 'biblio-mobile-app',
    authDomain: 'biblio-mobile-app.firebaseapp.com',
    storageBucket: 'biblio-mobile-app.firebasestorage.app',
  );

}